name: AOT Compatibility

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
  workflow_dispatch:

jobs:
  aot-compatibility:
    name: AOT Test (${{ matrix.os }}, ${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x64
          - os: ubuntu-latest
            arch: x64
            runtime: linux-x64
          # Linux ARM64
          - os: ubuntu-24.04-arm
            arch: arm64
            runtime: linux-arm64
          # Windows x64
          - os: windows-latest
            arch: x64
            runtime: win-x64
          # Windows ARM64
          - os: windows-11-arm
            arch: arm64
            runtime: win-arm64
          # macOS x64
          - os: macos-13
            arch: x64
            runtime: osx-x64
          # macOS ARM64 (Apple Silicon)
          - os: macos-latest
            arch: arm64
            runtime: osx-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          global-json-file: global.json
          source-url: https://nuget.pkg.github.com/open-feature/index.json

      - name: Cache NuGet packages
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ matrix.arch }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-nuget-
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build -c Release --no-restore

      - name: Test AOT compatibility project build
        run: dotnet build test/OpenFeature.AotCompatibility/OpenFeature.AotCompatibility.csproj -c Release --no-restore

      - name: Publish AOT compatibility test (cross-platform)
        run: |
          dotnet publish test/OpenFeature.AotCompatibility/OpenFeature.AotCompatibility.csproj \
            -c Release \
            -r ${{ matrix.runtime }} \
            -o ./aot-output

      - name: Run AOT compatibility test
        shell: pwsh
        run: |
          if ("${{ runner.os }}" -eq "Windows") {
            ./aot-output/OpenFeature.AotCompatibility.exe
          } else {
            chmod +x ./aot-output/OpenFeature.AotCompatibility
            ./aot-output/OpenFeature.AotCompatibility
          }

      - name: Upload AOT artifacts
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: aot-binaries-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            aot-output
          retention-days: 7

  aot-size-comparison:
    name: AOT Size Comparison
    needs: aot-compatibility
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Download all AOT artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          pattern: aot-binaries-*
          path: ./artifacts

      - name: Generate size comparison report
        shell: pwsh
        run: |
          "# AOT Binary Size Report" | Out-File -FilePath size_report.md -Encoding utf8
          "" | Out-File -FilePath size_report.md -Append -Encoding utf8
          "| Platform | Architecture | AOT Test Binary | AspNetCore Sample |" | Out-File -FilePath size_report.md -Append -Encoding utf8
          "|----------|--------------|-----------------|-------------------|" | Out-File -FilePath size_report.md -Append -Encoding utf8

          $artifactDirs = Get-ChildItem -Path ./artifacts -Directory -Name "aot-binaries-*"

          foreach ($dir in $artifactDirs) {
            $fullPath = "./artifacts/$dir"
            if (Test-Path -Path $fullPath -PathType Container) {
              $platform = ($dir -replace '^aot-binaries-', '') -replace '-[^-]*$', ''
              $arch = ($dir -split '-')[-1]

              # Find the AOT test binary
              $aotSize = "N/A"
              if (Test-Path "$fullPath/aot-output/OpenFeature.AotCompatibility.exe") {
                $aotSize = (Get-Item "$fullPath/aot-output/OpenFeature.AotCompatibility.exe").Length
              } elseif (Test-Path "$fullPath/aot-output/OpenFeature.AotCompatibility") {
                $aotSize = (Get-Item "$fullPath/aot-output/OpenFeature.AotCompatibility").Length
              }

              # Format sizes
              if ($aotSize -ne "N/A") {
                $aotSizeMb = [math]::Round($aotSize / 1048576, 2)
                $aotDisplay = "$aotSizeMb" + "MB"
              } else {
                $aotDisplay = "N/A"
              }

              $aspnetDisplay = "N/A"  # AspNetCore sample not implemented yet

              "| $platform | $arch | $aotDisplay | $aspnetDisplay |" | Out-File -FilePath size_report.md -Append -Encoding utf8
            }
          }

          "" | Out-File -FilePath size_report.md -Append -Encoding utf8
          "Generated on: $(Get-Date)" | Out-File -FilePath size_report.md -Append -Encoding utf8

          Get-Content size_report.md

      - name: Find PR Comment
        uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e # v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "AOT Binary Size Report"

      - name: Create or update PR comment
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: size_report.md
          edit-mode: replace
