name: E2E Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
  merge_group:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5
        with:
          global-json-file: global.json

      - name: Cache NuGet packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', 'Directory.Packages.props', 'global.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Initialize Tests
        run: |
          git submodule update --init --recursive
          cp spec/specification/assets/gherkin/*.feature test/OpenFeature.E2ETests/Features/

      - name: Run Tests
        run: dotnet test test/OpenFeature.E2ETests/ --configuration Release --report-github
